"""
app/agents/reporter_agent.py
Unit 2 — Final report generation agent.

Receives handoff from the Analysis Agent and generates:
  1. A structured Markdown defect report
  2. A JSON payload for downstream systems (n8n, tickets, etc.)

Multi-agent handoff chain:
  Triage Agent -> Analysis Agent -> Reporter Agent
"""

import os
import json
import uuid
from datetime import datetime
from google import genai
from google.genai import types
from dotenv import load_dotenv

from app.memory.session_store import get_history, save_defect_report
from app.tools.n8n_tool import send_defect_to_n8n

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")
MODEL_NAME = "gemini-2.5-flash"

REPORTER_SYSTEM_PROMPT = """You are ReportWriter, a professional technical documentation agent.

Generate a structured software defect report in this EXACT Markdown format:

---
# Defect Report — [DEFECT-ID]

**Date:** [date]
**Severity:** [Low/Medium/High/Critical]
**Component:** [component name]
**Status:** Open

## Executive Summary
[2-3 sentence summary]

## Defect Description
[Detailed description]

## Steps to Reproduce
1. [Step 1]
2. [Step 2]
3. [Step 3]

## Expected Behavior
[What should happen]

## Actual Behavior
[What actually happens]

## Root Cause Hypothesis
[Technical analysis]

## Impact Assessment
- **Users Affected:** [estimate]
- **Business Impact:** [description]
- **Data Risk:** [Low/Medium/High]

## Recommended Fix
[Specific technical recommendation]

## Priority Score
[X/30] — [Justification]

---
*Generated by AI-Based Defect Reporting System*
"""


def generate_report(
    defect_description: str,
    analysis_response: str,
    session_id: str,
    severity: str = "Medium",
    component: str = "Unknown",
    send_to_n8n: bool = True,
) -> dict:
    """
    Generate a structured defect report from analysis data.
    """
    defect_id = f"DEF-{uuid.uuid4().hex[:6].upper()}"
    date_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    print(f"\n[REPORTER] Generating report {defect_id}...")

    prompt = (
        f"Generate a defect report for:\n\n"
        f"DEFECT ID: {defect_id}\n"
        f"DATE: {date_str}\n"
        f"PREDICTED SEVERITY: {severity}\n"
        f"COMPONENT: {component}\n\n"
        f"ORIGINAL DEFECT DESCRIPTION:\n{defect_description}\n\n"
        f"ANALYSIS AGENT FINDINGS:\n{analysis_response}\n\n"
        f"Generate the complete structured Markdown report now."
    )

    markdown_report = ""
    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=types.GenerateContentConfig(
                system_instruction=REPORTER_SYSTEM_PROMPT,
            ),
        )
        markdown_report = response.text
    except Exception as e:
        print(f"[REPORTER] Gemini failed: {e}. Switching to Groq fallback...")
        try:
            from app.llm_fallback import call_groq_chat
            markdown_report = call_groq_chat(
                prompt=prompt,
                system_prompt=REPORTER_SYSTEM_PROMPT,
                max_tokens=1500,
            )
        except Exception as groq_err:
            print(f"[REPORTER] Groq fallback failed: {groq_err}")
            markdown_report = (
                f"# Defect Report — {defect_id}\n\n"
                f"**Date:** {date_str}\n"
                f"**Severity:** {severity}\n"
                f"**Component:** {component}\n"
                f"**Status:** Open\n\n"
                f"## Executive Summary\n{defect_description[:200]}\n\n"
                f"## Analysis\n{analysis_response[:500]}\n\n"
                f"*Report generation notice: {str(e)}*\n"
            )


    json_report = {
        "defect_id": defect_id,
        "created_at": date_str,
        "session_id": session_id,
        "title": defect_description[:100],
        "description": defect_description,
        "component": component,
        "severity": severity,
        "status": "Open",
        "analysis_summary": analysis_response[:500],
        "markdown_report": markdown_report,
    }

    try:
        save_defect_report(session_id, json_report)
        print(f"[REPORTER] Report {defect_id} saved to SQLite")
    except Exception as e:
        print(f"[REPORTER] DB save error: {e}")

    n8n_status = ""
    if send_to_n8n:
        n8n_status = send_defect_to_n8n(
            session_id=session_id,
            title=defect_description[:100],
            description=defect_description,
            component=component,
            severity=severity,
            reporter="AI Analysis System",
            report_markdown=markdown_report,
        )
        print(f"[REPORTER] n8n status: {n8n_status[:80]}")

    return {
        "defect_id": defect_id,
        "markdown_report": markdown_report,
        "json_report": json_report,
        "n8n_status": n8n_status,
    }


if __name__ == "__main__":
    result = generate_report(
        defect_description="Login page crashes with 500 error on Firefox",
        analysis_response="Root cause: unhandled null reference in auth middleware.",
        session_id="test-session",
        severity="High",
        component="Authentication",
        send_to_n8n=True,
    )
    print(result["markdown_report"][:500])
